<h1>=== Importing Libraries ===</h1>

In [247]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [248]:
data = pd.read_csv("data/BIKE DETAILS.csv")
data.head()

name  selling_price  year seller_type  \
0            Royal Enfield Classic 350         175000  2019  Individual   
1                            Honda Dio          45000  2017  Individual   
2  Royal Enfield Classic Gunmetal Grey         150000  2018  Individual   
3    Yamaha Fazer FI V 2.0 [2016-2018]          65000  2015  Individual   
4                Yamaha SZ [2013-2014]          20000  2011  Individual   

       owner  km_driven  ex_showroom_price  
0  1st owner        350                NaN  
1  1st owner       5650                NaN  
2  1st owner      12000           148114.0  
3  1st owner      23000            89643.0  
4  2nd owner      21000                NaN

In [249]:
data.tail()

name  selling_price  year seller_type      owner  \
1056           Activa 3g          17000  2010  Individual  1st owner   
1057    Honda CB twister          16000  2012  Individual  1st owner   
1058  Bajaj Discover 125          15000  2013  Individual  2nd owner   
1059      Honda CB Shine          12000  2009  Individual  1st owner   
1060    Bajaj Pulsar 150          10000  2008  Individual  1st owner   

      km_driven  ex_showroom_price  
1056     500000            52000.0  
1057      33000            51000.0  
1058      35000            57000.0  
1059      53000            58000.0  
1060      92233            75000.0

In [250]:
data.shape

(1061, 7)

In [251]:
data.describe()

selling_price         year      km_driven  ex_showroom_price
count    1061.000000  1061.000000    1061.000000       6.260000e+02
mean    59638.151744  2013.867107   34359.833176       8.795871e+04
std     56304.291973     4.301191   51623.152702       7.749659e+04
min      5000.000000  1988.000000     350.000000       3.049000e+04
25%     28000.000000  2011.000000   13500.000000       5.485200e+04
50%     45000.000000  2015.000000   25000.000000       7.275250e+04
75%     70000.000000  2017.000000   43000.000000       8.703150e+04
max    760000.000000  2020.000000  880000.000000       1.278000e+06

In [252]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1061 entries, 0 to 1060
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   name               1061 non-null   object 
 1   selling_price      1061 non-null   int64  
 2   year               1061 non-null   int64  
 3   seller_type        1061 non-null   object 
 4   owner              1061 non-null   object 
 5   km_driven          1061 non-null   int64  
 6   ex_showroom_price  626 non-null    float64
dtypes: float64(1), int64(3), object(3)
memory usage: 58.1+ KB


In [253]:
data.isna().sum()

name                   0
selling_price          0
year                   0
seller_type            0
owner                  0
km_driven              0
ex_showroom_price    435
dtype: int64

In [254]:
data = data.dropna()

In [255]:
data.isna().sum()

name                 0
selling_price        0
year                 0
seller_type          0
owner                0
km_driven            0
ex_showroom_price    0
dtype: int64

In [208]:
data.columns

Index(['Car Name', 'Displacement', 'Enginee', 'HP', 'Transmission',
       'Top-speed', 'Cost'],
      dtype='object')

In [256]:
data.corr()['selling_price']

selling_price        1.000000
year                 0.350654
km_driven           -0.194093
ex_showroom_price    0.918583
Name: selling_price, dtype: float64

In [257]:
X = data[['year', 'km_driven', 'ex_showroom_price']].values
X

array([[  2018.,  12000., 148114.],
       [  2015.,  23000.,  89643.],
       [  2010.,  60000.,  53857.],
       ...,
       [  2013.,  35000.,  57000.],
       [  2009.,  53000.,  58000.],
       [  2008.,  92233.,  75000.]])

In [258]:
y = data['selling_price'].values
y

array([150000,  65000,  18000,  78500,  50000,  35000,  28000,  80000,
       365000,  25000,  40000, 150000, 120000,  26000,  32000,  25000,
        42000,  40000,  55000,  38000,  43000,  62000,  60000,  45000,
       120000,  50000,  28000,  85000,  29900,  25000,  30000,  60000,
        35000,  25000,  30000,  35000,  70000,  25000,  35000,  50000,
        30000,  48000,  65000,  45000,  34000, 165000,  65000, 165000,
        50000,  62000,  30000,  28000,  30000, 140000,  30000,  22000,
        22989,  42000,  30000,  45000, 150000,  24999, 150000,  42000,
        50000, 120000,  17500,  57000,  25000, 160000, 135000,  55000,
        20000,  55000,  50000,  60000,  40000,  15000, 750000, 190000,
       130000,  54786,  35000,  45000, 100000,  20000,  60000,  22000,
        30000,  28000,  40000, 100000,  48000,  20000,  23000,  15000,
        35000,  25000,  45000,  25000,  35000,  25000,  25000,  75000,
        47999,  25000,  50000,  65000,  60000,  20000,  27000,  35000,
      

In [259]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=.25, random_state=15)

In [260]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(469, 3)
(157, 3)
(469,)
(157,)


In [261]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [262]:
y_pred = model.predict(X_test)   
y_pred

array([ 29035.64520604,  30133.0906705 ,  59639.30200789,  63748.89089724,
        11519.66103599,  34262.39961907,    278.15488922, 131118.24268544,
        29110.51997981,  66742.80544446,  23486.03085057,  57853.76236944,
        32720.78426767,  93604.06227809, 127214.91688269,  41319.68039149,
        52803.96258034,  14583.73493287, 101220.87410172,  43501.74147603,
        46926.95944745,  35312.49620465,  22484.39570815,  19721.53046321,
        37266.59435466,  -3906.37572613,  53406.20519367,  93606.474003  ,
        29368.26620517,  50318.70417917,  46745.35804865,  49742.88220027,
        48657.41474331,  41468.96201877,  45702.74761924,  60191.61029955,
        41745.71404737,  40288.20006029,  98471.08190965,  59142.05762343,
        56191.801354  ,  45891.14739305,  34301.39916117,  45336.98996107,
        24379.3519588 ,  22449.05832724,  20174.37958548, 137586.75308925,
        59257.70576197,  54695.12978773, 113239.97633596, 131583.04980266,
        60163.17031683,  

In [263]:
data_predicted = pd.DataFrame({'Actual': y_test, 'Predicted': np.around(y_pred)})
data_predicted

Actual  Predicted
0     25000    29036.0
1     34000    30133.0
2     45000    59639.0
3     45000    63749.0
4     21000    11520.0
..      ...        ...
152   30000    25618.0
153  130000   125202.0
154   26000    35500.0
155   18000    12401.0
156   60000    73317.0

[157 rows x 2 columns]

In [264]:
model.score(X_test, y_test)

0.799620458588633

In [265]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(model, X_train, y_train, cv=10)
scores

array([0.86843672, 0.88405048, 0.87142325, 0.82579198, 0.77615511,
       0.87712154, 0.87984178, 0.82529071, 0.91929895, 0.78314276])